name: OrangeFox Recovery Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Подготовка Linux-окружения
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc zip cpio python3 git curl
        
    - name: Сборка OrangeFox через автоматический экшен
      uses: up7m/recovery-action@main
      with:
        manifest_url: https://github.com
        manifest_branch: fox_12.1
        device_vendor: oneplus
        device_code: OP6505L1
        device_path: device/oneplus/OP6505L1
        targettype: recovery
