    - name: Компиляция OrangeFox Recovery
      run: |
        cd ~/fox_12.1
        source build/envsetup.sh
        lunch omni_OP6505L1-eng
        # Собираем полноценный boot-образ с рекавери внутри
        mka bootimage

    - name: Выгрузка готового рекавери в артефакты
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-OnePlus-Nord-CE-6
        path: ~/fox_12.1/out/target/product/OP6505L1/boot.img
